/*
 * generated by Xtext 2.35.0
 */
package tools.vitruv.emftemplate.dsl;

import com.google.inject.Injector;

import tools.vitruv.emftemplate.model.ModelPackage;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ExampleLanguageStandaloneSetup extends ExampleLanguageStandaloneSetupGenerated {

    @Override
    public Injector createInjectorAndDoEMFRegistration() {
        ModelPackage.eINSTANCE.eClass();
        return super.createInjectorAndDoEMFRegistration();
    }

    public static void doSetup() {
        new ExampleLanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
    }
}
