/*
 * generated by Xtext 2.35.0
 */
package tools.vitruv.emftemplate.imports.dsl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ImportsLanguageStandaloneSetup extends ImportsLanguageStandaloneSetupGenerated {

    @Override
    public Injector createInjectorAndDoEMFRegistration() {
        EcorePlugin.ExtensionProcessor.process(null);
        return super.createInjectorAndDoEMFRegistration();
    }

    public static void doSetup() {
        new ImportsLanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
    }
    
}
