/*
 * generated by Xtext 2.35.0
 */
package tools.vitruv.emftemplate.imports.dsl;

import tools.vitruv.emftemplate.imports.dsl.linking.ImportsLanguageLinkingService;

import org.eclipse.xtext.linking.ILinkingService;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ImportsLanguageRuntimeModule extends AbstractImportsLanguageRuntimeModule {

    @Override
    public Class<? extends ILinkingService> bindILinkingService() {
        return ImportsLanguageLinkingService.class;
    }

}
