/*
 * generated by Xtext 2.35.0
 */
package tools.vitruv.emftemplate.dsl.validation;

import org.eclipse.xtext.validation.Check;

import tools.vitruv.emftemplate.model.Component;
import tools.vitruv.emftemplate.model.ModelPackage;
import tools.vitruv.emftemplate.model.Protocol;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class ExampleLanguageValidator extends AbstractExampleLanguageValidator {
    
    public static final String INVALID_NAME = "invalidName";

    @Check
    public void checkCapitalFirstLetter(Component component) {
        if (!Character.isUpperCase(component.getName().charAt(0))) {
            error("Name must start with a capital", ModelPackage.Literals.COMPONENT__NAME, INVALID_NAME);
        }
    }

    @Check
    public void checkCapitalFirstLetter(Protocol protocol) {
        if (!Character.isUpperCase(protocol.getName().charAt(0))) {
            warning("Name should start with a capital", ModelPackage.Literals.PROTOCOL__NAME, INVALID_NAME);
        }
    }
    
}
